/* global Meteor */
import { Pages } from '/imports/api/collections/pages'

Meteor.startup(() => {
  if (Pages.find({ slug: 'about-us' }).count() <= 0) {
    Pages.insert({
      title: 'About Us',
      slug: 'about-us',
      content: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum lacinia tincidunt. Duis a molestie turpis. Cras quam nisl, tincidunt non tellus eu, interdum cursus felis. Etiam sit amet tincidunt mauris. Fusce molestie sollicitudin lacus a rhoncus. Sed non enim sagittis, blandit ipsum non, maximus felis. Maecenas nec euismod urna, eget euismod metus. Nunc elementum fringilla diam non auctor. Sed mattis pharetra imperdiet.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc leo libero, tempus ut enim ut, tincidunt finibus leo. Aenean tristique lectus facilisis tellus dictum pretium. Maecenas eu odio nec urna dignissim mollis. Nam bibendum orci vitae felis sodales, id consequat velit fermentum. Nullam feugiat mauris tortor, ac blandit augue ullamcorper ut. Pellentesque quis dignissim enim, nec maximus dolor. Donec sed tempor lacus. Sed vehicula tincidunt viverra. Proin faucibus quis arcu eget facilisis. Nullam vel eros nisl. Nulla efficitur orci ac nunc pretium imperdiet laoreet a elit. Nullam cursus nibh et turpis laoreet, vel imperdiet nibh placerat. Aliquam auctor cursus mauris feugiat condimentum. Cras quis est justo.</p><p>Fusce ultrices elementum orci vel malesuada. Duis blandit eleifend mauris at iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla non dapibus arcu. Integer suscipit porta purus, et facilisis justo malesuada id. Vestibulum sodales, arcu at lacinia pellentesque, ipsum mi posuere quam, sit amet suscipit lorem diam vel lacus. Nam non risus augue. Aenean efficitur dictum nunc euismod egestas. Integer auctor sollicitudin porta. Donec eu vehicula mi. Ut porta tortor sed nunc tristique, quis pulvinar neque finibus. Vestibulum ac ligula enim. Maecenas auctor molestie eros at bibendum. Curabitur nibh nisl, malesuada ut turpis id, scelerisque accumsan ligula.</p><p>Vestibulum interdum quis dolor vel mattis. Fusce sodales fermentum lacinia. Vivamus lobortis nulla eget mauris condimentum sollicitudin. Proin dignissim suscipit facilisis. Ut efficitur aliquet laoreet. Fusce nec velit cursus, aliquam sapien a, sagittis tellus. Proin neque risus, convallis sed nunc vel, venenatis accumsan magna. Suspendisse potenti. Nam lobortis nisi eu mi sodales porttitor.</p><p>Sed sed tristique neque, non interdum sapien. Vestibulum pretium consectetur turpis eget maximus. Vivamus vel consectetur metus. Donec eu orci mollis, auctor ligula eget, blandit enim. Etiam purus ex, lacinia sit amet sollicitudin sed, sollicitudin et mi. Vestibulum euismod cursus augue, eget egestas ipsum rhoncus pellentesque. Sed eget justo in augue bibendum accumsan. Phasellus sollicitudin tortor nunc, eu rhoncus tellus vehicula a. Nunc congue velit metus, at iaculis ex dictum eu. Aenean auctor libero id turpis dictum porta. Ut risus lorem, dapibus ut purus quis, finibus vulputate ex.</p>'
    })
  }
})
